Add support for SmartAsserts.jl
mauro3/Parameters.jl pull request #152
Opened 2023-04-16 12:45 UTC by Zentrik

It should be easy to add any other similar package such as ArgChecks.jl

2023-04-30 21:50 UTC, mauro3 commented
Thanks!

Comments:
- adding this feature would be good
- shouldn't ArgCheck.jl be implemented as on https://github.com/MrVPlusOne/SmartAsserts.jl it states that that package is preferred?
- The tests don't actually test the functionality or am I missing something?

x-ref: #120

2023-05-02 21:24 UTC, Zentrik commented
I decided not to use ArgCheck as it's ability to compile out asserts is not supported on new versions of julia, [OptionalArgChecks.jl](https://github.com/simeonschaub/OptionalArgChecks.jl) is broken on >= 1.5.
I would have added ArgCheck as well in this pr but I couldn't figure out a way to add the test without just copy and pasting them, which I didn't want to do as otherwise you would have 3 copies of near identical tests. If you don't care about this I can add that ArgCheck as well.

I've updated the tests, thanks for spotting that.

The main problem now is I didn't notice SmartAssert has set its compat to julia 1.5, I'll see if I can get that changed.

2023-06-18 17:30 UTC, Zentrik commented
This should be ready to be merged in now.

2023-06-20 09:44 UTC, mauro3 requested changes
Thanks for adding the tests!  There are still a few bits to do.  Also, let's move the compat for Julia to 1.5.

2023-06-20 09:44 UTC, mauro3 commented on Manifest.toml
> +# This file is machine-generated - editing it directly is not advised
This file should not be included in the PR

2023-06-20 09:44 UTC, mauro3 commented on Project.toml
Let's just move compat to Julia 1.5

2023-06-20 09:44 UTC, mauro3 commented on Project.toml
> +Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Shouldn't you just add `SmartAsserts` here and drop `Pkg`?  Then you can just use it in the tests.

2023-06-20 09:44 UTC, mauro3 commented on test/runtests.jl
> +@static if VERSION >= v"1.5" # Need static otherwise it tries to evaluate code below which fails
Dropping Julia 1.0 support will remove this.

2023-06-20 10:34 UTC, mauro3 approved these changes

2023-06-20 10:36 UTC, mauro3 commented
Sorry, one more thing: now we just need some docs!

2023-06-20 12:03 UTC, merged

2023-06-20 12:03 UTC, mauro3 commented
Thanks so much for your help!